### ISSUE TITLE
POPs tracker 2016-01

### ISSUE THREAD

**Issue by tomByrer** [jsdelivr/jsdelivr#9272]
CloudFlare
- [ ] [Oslo, Norway](https://blog.cloudflare.com/cloudflare-launches-new-data-centers-in-oslo-and-minneapolis/)
- [ ] Minneapolis, MN, USA
- [ ] [Perth Australia](https://blog.cloudflare.com/perth/)
- [ ] [Bangkok, Thailand: CloudFlare](https://blog.cloudflare.com/bangkok/)
- [ ] [Denver, CO, USA](https://blog.cloudflare.com/denver/) 
- [ ] [Denver, CO, USA](https://blog.cloudflare.com/denver/)
- [ ] [Moscow, Russia](https://blog.cloudflare.com/moscow/)

KeyCDN
- [ ] [Montreal, Canada](https://www.keycdn.com/blog/pop-in-canada/)

Fix:
- [ ]  [KeyCDN](https://www.keycdn.com/network) is in Syndey Australia, not Melbourne

**Comment by tomByrer** [comment]
I guess updates every 3 months are good enough ;)

**Comment by jimaek** [comment]
https://blog.cloudflare.com/taipei/

**Comment by tomByrer** [comment]
Ahh you beat me to it.

**Comment by jimaek** [comment]
https://blog.cloudflare.com/kiev/

**Comment by tomByrer** [comment]
Had anything to do with Kiev @jimaek ?

**Comment by jimaek** [comment]
I lived there for 2 months. Thats it :)

**Comment by tomByrer** [comment]
[Bangkok, Thailand: CloudFlare](https://blog.cloudflare.com/bangkok/)

**Comment by tomByrer** [comment]
Perhaps update at least 2x / year?  :)
